spring:
  application:
    name: demo

stripe:
  api:
    url: https://api.stripe.com
  enabled: true
  timeout: 10
  supportedCurrencies: USD,EUR,GBP

payment:
  type: paypal

email:
  host: localhost
  port: 25

# 存储类型
repository:
  type: database

# 通知类型
notification:
  type: email