spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver  # 添加这一行以明确指定驱动程序

stripe:
  api:
    url: https://api.stripe.com
  enabled: true
  timeout: 10
  supportedCurrencies: USD,EUR,GBP

payment:
  type: paypal

email:
  host: localhost
  port: 25

# 存储类型
repository:
  type: database

# 通知类型
notification:
  type: email